import { expect, test } from "@playwright/test";
import { expectHealthy, latestEmailHtml, signIn } from "./helpers";

const PAGES: Array<[string, string | RegExp]> = [
  ["/", "Dashboard"],
  ["/radar/projects", "Radar projects"],
  ["/radar/leads", "Leads"],
  ["/seo/location", "Location pages"],
  ["/seo/project", "Project pages"],
  ["/seo/blog", "Blog"],
  ["/seo/topics", "Blog topics"],
  ["/visibility", "AI visibility"],
  ["/properties", "Properties"],
  ["/towns", "Towns"],
  ["/settings", "Settings"],
  ["/team", "Team"],
  ["/jobs", "Job runs"],
  ["/usage", "API usage"],
  ["/account", "Account"],
];

test("signed-out visitors go to the login page", async ({ page }) => {
  await page.goto("/radar/leads");
  await expect(page).toHaveURL(/\/login$/);
});

test("admin can open every page", async ({ page }) => {
  await signIn(page, "admin");
  for (const [path, heading] of PAGES) {
    await page.goto(path);
    await expectHealthy(page, heading);
  }
});

test("roles limit what people can open", async ({ page }) => {
  await signIn(page, "editor");
  await expect(page.getByRole("link", { name: "Location pages" }).first()).toBeVisible();
  await expect(page.getByRole("link", { name: "Leads" })).toHaveCount(0);
  await page.goto("/radar/leads");
  await expect(page).toHaveURL(/forbidden=1/);
  await page.goto("/team");
  await expect(page).toHaveURL(/forbidden=1/);
});

test("admin invites a teammate who accepts and sets a password", async ({ page, browser }) => {
  const email = `invitee-${Date.now()}@e2e.test`;
  await signIn(page, "admin");
  await page.goto("/team");
  await expect(page.getByRole("cell", { name: /admin@e2e\.test/ })).toBeVisible();
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Role", { exact: true }).selectOption("editor");
  await page.getByRole("button", { name: "Send invite" }).click();
  await expect(page.getByText(`Invite sent to ${email} as editor.`)).toBeVisible();
  await page.reload();
  await expect(page.getByRole("cell", { name: email })).toBeVisible();

  const html = await latestEmailHtml(email);
  const link = html.match(/href="([^"]*\/auth\/confirm[^"]*)"/)?.[1]?.replace(/&amp;/g, "&");
  expect(link, "invite email links to /auth/confirm").toBeTruthy();

  const ctx = await browser.newContext();
  const invitee = await ctx.newPage();
  await invitee.goto(link!);
  await expect(invitee).toHaveURL(/\/account\?welcome=1/);
  await invitee.getByLabel("New password").fill("invitee-password-1");
  await invitee.getByLabel("Confirm").fill("invitee-password-1");
  await invitee.getByRole("button", { name: "Save password" }).click();
  await expect(invitee.getByText("Password saved.")).toBeVisible();
  await ctx.close();

  const fresh = await browser.newContext();
  const again = await fresh.newPage();
  await signIn(again, email, "invitee-password-1");
  await expect(again.getByRole("link", { name: "Location pages" }).first()).toBeVisible();
  await fresh.close();

  // Admin removes access again.
  page.once("dialog", (d) => d.accept());
  await page.getByRole("combobox", { name: `Role for ${email}` }).selectOption("");
  await expect(page.getByText("Access removed.")).toBeVisible();
});

test("admin can't remove their own admin role", async ({ page }) => {
  await signIn(page, "admin");
  await page.goto("/team");
  await expect(page.getByRole("combobox", { name: "Role for admin@e2e.test" })).toBeDisabled();
});

test("sales adds, reorders and deletes property photos", async ({ page }) => {
  await signIn(page, "sales");
  await page.goto("/properties");
  await page.getByRole("button", { name: "E2E Photo House" }).click();
  const png = (color: string) =>
    Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="40" height="30"><rect width="40" height="30" fill="${color}"/></svg>`
    );
  // Real PNGs are generated by drawing SVGs in the page, so no binary fixtures are needed.
  const files = await page.evaluate(
    async (svgs: string[]) => {
      const out: Array<{ name: string; data: number[] }> = [];
      for (const [i, svg] of svgs.entries()) {
        const img = new Image();
        img.src = `data:image/svg+xml;base64,${btoa(svg)}`;
        await img.decode();
        const c = document.createElement("canvas");
        c.width = 400;
        c.height = 300;
        c.getContext("2d")!.drawImage(img, 0, 0, 400, 300);
        const blob = await new Promise<Blob>((r) => c.toBlob((b) => r(b!), "image/png"));
        out.push({ name: `photo-${i}.png`, data: [...new Uint8Array(await blob.arrayBuffer())] });
      }
      return out;
    },
    [png("#0f2440").toString(), png("#f26b1d").toString()]
  );
  await page
    .locator('input[type="file"][accept^="image"]')
    .setInputFiles(
      files.map((f) => ({ name: f.name, mimeType: "image/png", buffer: Buffer.from(f.data) }))
    );
  const photos = page.getByRole("img", { name: /^Photo \d$/ });
  await expect(photos).toHaveCount(2);
  await expect(page.getByText("Cover", { exact: true })).toBeVisible();
  const first = await photos.nth(0).getAttribute("src");
  const second = await photos.nth(1).getAttribute("src");
  expect(first).toContain("/storage/v1/object/public/property-photos/");
  const res = await page.request.get(first!);
  expect(res.ok()).toBe(true);
  expect(res.headers()["content-type"]).toBe("image/jpeg");

  await page.getByRole("button", { name: "Move later" }).first().click();
  await expect(photos.nth(0)).toHaveAttribute("src", second!);

  page.once("dialog", (d) => d.accept());
  await page.getByRole("button", { name: "Delete photo" }).first().click();
  await expect(photos).toHaveCount(1);

  await page.keyboard.press("Escape");
  await page.reload();
  await expect(page.getByText("1 photo")).toBeVisible();
  expect((await page.request.get(second!)).status()).toBeGreaterThanOrEqual(400);
});
