#!/usr/bin/env node
// Copies packages/core/src into supabase/functions/_shared/core so edge functions deploy it.
// `--check` fails if the copy is stale (used in CI).
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const src = join(root, "packages/core/src");
const dest = join(root, "supabase/functions/_shared/core");
const header =
  "// GENERATED by scripts/sync-core.mjs from packages/core/src. Do not edit; run `pnpm sync:core`.\n";
const check = process.argv.includes("--check");

const files = readdirSync(src).filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"));
const expected = new Map(files.map((f) => [f, header + readFileSync(join(src, f), "utf8")]));

if (check) {
  const actual = existsSync(dest) ? readdirSync(dest).filter((f) => f.endsWith(".ts")) : [];
  const stale = [
    ...[...expected.keys()].filter(
      (f) => !actual.includes(f) || readFileSync(join(dest, f), "utf8") !== expected.get(f)
    ),
    ...actual.filter((f) => !expected.has(f)),
  ];
  if (stale.length) {
    console.error(
      `supabase/functions/_shared/core is out of date (${stale.join(", ")}). Run: pnpm sync:core`
    );
    process.exit(1);
  }
  console.log("core copy is up to date");
} else {
  rmSync(dest, { recursive: true, force: true });
  mkdirSync(dest, { recursive: true });
  for (const [f, content] of expected) writeFileSync(join(dest, f), content);
  console.log(`synced ${expected.size} files to supabase/functions/_shared/core`);
}
