// GENERATED by scripts/sync-core.mjs from packages/core/src. Do not edit; run `pnpm sync:core`.
import type { LocationDataPack, ProjectDataPack } from "./datapack.ts";
import { asInt, asString } from "./json.ts";
import { BANNED_PHRASES } from "./quality.ts";
import { slugify, truncate } from "./text.ts";
import type { CompanyFacts } from "./types.ts";

export interface Faq {
  question: string;
  answer: string;
}

export interface Section {
  heading: string;
  body_markdown: string;
}

export interface PageDraft {
  title: string;
  meta_description: string;
  h1: string;
  intro: string;
  sections: Section[];
  faqs: Faq[];
}

export interface BlogDraft {
  title: string;
  meta_description: string;
  excerpt: string;
  body_markdown: string;
  faqs: Faq[];
}

export interface InternalLink {
  href: string;
  label: string;
  kind: "town" | "project" | "blog" | "quote" | "hub";
}

const SHARED_RULES = (facts: CompanyFacts) => `Facts about ${facts.name} you may state: direct operator (no agency markup); whole houses of ${facts.property_bedrooms_min}-${facts.property_bedrooms_max} bedrooms; ${facts.included.join(", ")} included; priced per person per night (pppn); same-day quotes; 24/7 UK support; weekly and monthly terms; ${facts.credit_terms_days_min}-${facts.credit_terms_days_max} day credit terms for approved accounts; phone ${facts.phone}.

Hard rules:
- British English. Short sentences. Written for site managers, project managers and procurement.
- Use ONLY numbers that appear in the DATA PACK or the facts above. Never invent properties, prices, distances, projects, dates, statistics or reviews. If a figure is missing, write around it without a number.
- Do not name individual properties or give street addresses.
- Never use these words or phrases: ${BANNED_PHRASES.join(", ")}.
- No exclamation marks. No hype.`;

const PAGE_JSON_SHAPE = `Return ONLY a JSON object:
{"title": string (max 60 chars), "meta_description": string (max 155 chars), "h1": string, "intro": string (2-3 sentences, plain text), "sections": [{"heading": string, "body_markdown": string}], "faqs": [{"question": string, "answer": string}]}
Markdown in body_markdown may use paragraphs, "-" bullet lists, **bold** and pipe tables. Do not include the H1 or H2 headings inside body_markdown; they are rendered from "heading".`;

export function buildLocationPageSystem(brandVoice: string, facts: CompanyFacts): string {
  return `You write location landing pages for ${facts.name} (${facts.website}), which rents whole houses to construction and infrastructure crews working away from home.

Brand voice: ${brandVoice}

${SHARED_RULES(facts)}

${PAGE_JSON_SHAPE}`;
}

export function buildLocationPagePrompt(pack: LocationDataPack, links: InternalLink[]): string {
  const t = pack.town.name;
  const hasProjects = pack.projects.items.length > 0;
  const hasComparison = !!pack.cost_comparison;
  const sections = [
    `"Houses for crews near ${t}" - what we have within ${pack.properties.radius_miles} miles (count, bedroom range, from pppn, distances) using the pack. If count is 0, say we source houses for crews in the area on request and invite a call; state no counts.`,
    hasProjects
      ? `"Major projects near ${t}" - the projects in the pack with distance from ${t}; explain what that means for crews.`
      : null,
    hasComparison
      ? `"Hotel vs whole house cost for a crew of ${pack.cost_comparison!.crew_size}" - include a markdown table built ONLY from cost_comparison (columns: Period, Hotel, Whole house, Saving). Mention the hotel figure is a typical local rate.`
      : `"Hotel vs whole house" - explain the cost logic (per person per night, bills included, one house instead of several rooms) without any figures.`,
    `"What's included" - ${pack.company.included.join(", ")}, kitchens and shared living space.`,
    `"Parking and vans" - use with_van_parking and parking data if present.`,
    `"How booking works" - enquiry, same-day quote, weekly/monthly terms, credit terms, 24/7 support.`,
  ].filter(Boolean);
  return `Write the page "Contractor Accommodation in ${t}".

H1 must be exactly: Contractor Accommodation in ${t}
Intro: 2-3 sentences that directly answer "where can a contractor crew stay in ${t}?" with the most useful facts from the pack (this is what AI assistants quote).
Sections, in this order (omit any marked as omitted):
${sections.map((s, i) => `${i + 1}. ${s}`).join("\n")}
FAQs: 6-8 questions specific to ${t} (distances, projects, parking, crew sizes, costs from the pack).
Total length including FAQs: 700-1,200 words.
Where natural, link to these pages using markdown links (use the exact hrefs): ${links.map((l) => `[${l.label}](${l.href})`).join(", ")}.

DATA PACK:
${JSON.stringify({ ...pack, company: undefined }, null, 2)}`;
}

export function buildProjectPageSystem(brandVoice: string, facts: CompanyFacts): string {
  return `You write project accommodation guides for ${facts.name} (${facts.website}), which rents whole houses to construction and infrastructure crews working away from home.

Brand voice: ${brandVoice}

${SHARED_RULES(facts)}
- Describe the project only with facts in the pack. You may give widely known public context about the project (what it is) in one or two sentences, without numbers unless they are in the pack.

${PAGE_JSON_SHAPE}`;
}

export function buildProjectPagePrompt(pack: ProjectDataPack, links: InternalLink[]): string {
  const n = pack.project.name;
  return `Write the page "Accommodation near ${n}".

H1 must be exactly: Accommodation near ${n}
Intro: 2-3 sentences answering "where can crews working on ${n} stay?" with the most useful facts from the pack.
Sections, in this order:
1. "Where the ${n} site is" - location from the pack.
2. "Towns crews stay in" - the towns in the pack with our houses, distances and from-pppn. If there are none, say we source houses near the site on request; state no counts.
3. "Planning accommodation for your crew size" - use crew_planning.
4. ${pack.cost_comparison ? `"Hotel vs whole house cost" - a markdown table from cost_comparison only.` : `"Hotel vs whole house" - explain the cost logic without figures.`}
5. "What's included" - ${pack.company.included.join(", ")}.
6. "How booking works".
FAQs: 6-8 questions specific to ${n}.
Total length including FAQs: 700-1,200 words.
Where natural, link to: ${links.map((l) => `[${l.label}](${l.href})`).join(", ")}.

DATA PACK:
${JSON.stringify({ ...pack, company: undefined }, null, 2)}`;
}

export function buildBlogSystem(brandVoice: string, facts: CompanyFacts): string {
  return `You write practical blog posts for ${facts.name} (${facts.website}) for construction and infrastructure project managers, site managers and procurement teams who house crews away from home.

Brand voice: ${brandVoice}

${SHARED_RULES(facts)}
- For tax, HMRC or regulation topics: explain principles, link to the relevant gov.uk guidance, and include the line "Check current HMRC guidance before relying on this." Do not state tax thresholds, allowance amounts or rates.

Return ONLY a JSON object:
{"title": string (max 60 chars), "meta_description": string (max 155 chars), "excerpt": string (1-2 sentences), "body_markdown": string, "faqs": [{"question": string, "answer": string}]}
body_markdown: starts with a 2-3 sentence answer-first paragraph, then a "> **Key takeaways**" blockquote with 3-5 "- " bullets, then "## " and "### " sections. 1,200-1,800 words including FAQs. Do not include an H1.`;
}

export function buildBlogPrompt(topic: { keyword: string; working_title: string; intent: string | null }, links: InternalLink[], facts: Record<string, unknown> = {}): string {
  return `Write a blog post.
Working title: ${topic.working_title}
Target keyword: ${topic.keyword}
Search intent: ${topic.intent ?? "informational"}
Include 5 FAQs.
Link naturally to these pages using the exact hrefs: ${links.map((l) => `[${l.label}](${l.href})`).join(", ")}.
${Object.keys(facts).length ? `Verified data you may use:\n${JSON.stringify(facts, null, 2)}` : "No extra data is supplied: do not state local statistics."}`;
}

export const TOPICS_SYSTEM = `You plan blog content for StaysDirect, a UK operator renting whole houses (bills included, priced per person per night) to construction and infrastructure crews working away from home. Readers: project managers, site managers, procurement and logistics staff at contractors.

Return ONLY a JSON object: {"topics": [{"keyword": string, "working_title": string, "intent": "informational"|"commercial"|"transactional", "priority": integer 1-5, "source": "ai"}]}
Rules: practical topics only (cost guides, HMRC travel and subsistence principles, housing a crew of a given size, van parking, working-away checklists, project guides for major UK schemes, seasonal planning). No topic may duplicate or closely overlap an existing title. British English.`;

export function buildTopicsPrompt(args: { existingTitles: string[]; bigProjects: string[]; count: number; month: string }): string {
  return `Suggest ${args.count} new blog topics for ${args.month}.
Existing posts and queued topics (do not duplicate):
${args.existingTitles.map((t) => `- ${t}`).join("\n") || "- none"}
Recent large projects you may write guides for:
${args.bigProjects.map((t) => `- ${t}`).join("\n") || "- none"}`;
}

export const REVIEW_SYSTEM = `You are a strict editor reviewing a landing page for a UK contractor accommodation company before it is published.
Score 0-100 for: usefulness to a site manager, specificity to the location/project (not a template with the name swapped), clarity, and whether any claim looks unsupported by the data pack.
Return ONLY JSON: {"score": integer 0-100, "issues": [string, ...] (max 5, each under 25 words)}`;

export function buildReviewPrompt(draftMarkdown: string, pack: unknown): string {
  return `DATA PACK:\n${JSON.stringify(pack)}\n\nPAGE:\n${draftMarkdown}`;
}

function asFaqs(v: unknown): Faq[] {
  if (!Array.isArray(v)) return [];
  return v
    .map((f) => {
      const o = (f ?? {}) as Record<string, unknown>;
      const question = asString(o.question, 300);
      const answer = asString(o.answer, 2000);
      return question && answer ? { question, answer } : null;
    })
    .filter((f): f is Faq => !!f)
    .slice(0, 10);
}

export function validatePageDraft(raw: unknown, expectedH1: string): PageDraft {
  const o = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  const sections = Array.isArray(o.sections)
    ? o.sections
        .map((s) => {
          const so = (s ?? {}) as Record<string, unknown>;
          const heading = asString(so.heading, 200);
          const body = asString(so.body_markdown, 20_000);
          return heading && body ? { heading, body_markdown: body } : null;
        })
        .filter((s): s is Section => !!s)
    : [];
  return {
    title: asString(o.title, 200) ?? expectedH1,
    meta_description: asString(o.meta_description, 400) ?? "",
    h1: expectedH1,
    intro: asString(o.intro, 2000) ?? "",
    sections,
    faqs: asFaqs(o.faqs),
  };
}

export function validateBlogDraft(raw: unknown, fallbackTitle: string): BlogDraft {
  const o = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  return {
    title: asString(o.title, 200) ?? fallbackTitle,
    meta_description: asString(o.meta_description, 400) ?? "",
    excerpt: asString(o.excerpt, 600) ?? "",
    body_markdown: asString(o.body_markdown, 60_000) ?? "",
    faqs: asFaqs(o.faqs),
  };
}

export interface TopicIdea {
  keyword: string;
  working_title: string;
  intent: string;
  priority: number;
  source: string;
}

export function validateTopics(raw: unknown, existingTitles: string[]): TopicIdea[] {
  const o = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  const list = Array.isArray(o.topics) ? o.topics : Array.isArray(raw) ? raw : [];
  const existing = existingTitles.map((t) => slugify(t));
  const seen = new Set<string>();
  const out: TopicIdea[] = [];
  for (const item of list) {
    const t = (item ?? {}) as Record<string, unknown>;
    const title = asString(t.working_title, 200);
    const keyword = asString(t.keyword, 200);
    if (!title || !keyword) continue;
    const slug = slugify(title);
    if (seen.has(slug) || existing.some((e) => titleOverlap(e, slug) > 0.7)) continue;
    seen.add(slug);
    out.push({
      keyword,
      working_title: truncate(title, 100),
      intent: asString(t.intent, 40) ?? "informational",
      priority: asInt(t.priority, 1, 5) ?? 3,
      source: asString(t.source, 40) ?? "ai",
    });
  }
  return out;
}

/** Jaccard overlap of slug words, used to avoid near-duplicate blog topics. */
export function titleOverlap(a: string, b: string): number {
  const stop = new Set(["a", "the", "for", "of", "to", "in", "and", "uk", "how", "your", "guide", "what"]);
  const wa = new Set(a.split("-").filter((w) => w && !stop.has(w)));
  const wb = new Set(b.split("-").filter((w) => w && !stop.has(w)));
  if (!wa.size || !wb.size) return 0;
  let inter = 0;
  for (const w of wa) if (wb.has(w)) inter++;
  return inter / (wa.size + wb.size - inter);
}

export function validateReview(raw: unknown): { score: number; issues: string[] } {
  const o = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  return {
    score: asInt(o.score, 0, 100) ?? 50,
    issues: Array.isArray(o.issues) ? o.issues.map((i) => asString(i, 300)).filter((i): i is string => !!i).slice(0, 5) : [],
  };
}

/** The full reader-visible markdown of a page, used for word counts, checks and similarity. */
export function pageMarkdown(d: Pick<PageDraft, "h1" | "intro" | "sections" | "faqs">): string {
  return [
    d.intro,
    ...d.sections.map((s) => `## ${s.heading}\n\n${s.body_markdown}`),
    d.faqs.length ? `## Frequently asked questions\n\n${d.faqs.map((f) => `### ${f.question}\n\n${f.answer}`).join("\n\n")}` : "",
  ]
    .filter(Boolean)
    .join("\n\n");
}

export function blogMarkdown(d: Pick<BlogDraft, "body_markdown" | "faqs">): string {
  return [
    d.body_markdown,
    d.faqs.length ? `## Frequently asked questions\n\n${d.faqs.map((f) => `### ${f.question}\n\n${f.answer}`).join("\n\n")}` : "",
  ]
    .filter(Boolean)
    .join("\n\n");
}
