// GENERATED by scripts/sync-core.mjs from packages/core/src. Do not edit; run `pnpm sync:core`.
import { extractPostcodes, normalizePostcode } from "./geo.ts";
import { asEnum, asInt, asIsoDate, asString } from "./json.ts";
import { formatGbpCompact, truncate } from "./text.ts";
import {
  LOCATION_CONFIDENCES,
  PROJECT_TYPES,
  type LocationConfidence,
  type ProjectType,
  type RadarStatus,
} from "./types.ts";

export interface EnrichmentInput {
  title: string;
  description: string | null;
  buyer_name: string | null;
  buyer_postcode: string | null;
  supplier_name: string | null;
  value_gbp: number | null;
  cpv_codes: string[];
  delivery_text: string | null;
  delivery_postcodes: string[];
  start_date: string | null;
  end_date: string | null;
  duration_months: number | null;
}

export interface Enrichment {
  is_relevant: boolean;
  relevance_reason: string;
  project_type: ProjectType;
  site_location_text: string | null;
  site_postcode: string | null;
  site_town: string | null;
  location_confidence: LocationConfidence;
  est_workers_min: number | null;
  est_workers_max: number | null;
  est_workers_away_from_home: number | null;
  duration_months: number | null;
  start_date: string | null;
}

export const ENRICH_SYSTEM = `You analyse UK public-sector contract award notices for StaysDirect, which rents whole houses to construction and infrastructure crews working away from home.

Return ONLY a JSON object with exactly these keys:
{"is_relevant": boolean, "relevance_reason": string (max 30 words), "project_type": one of ${PROJECT_TYPES.map((t) => `"${t}"`).join("|")}, "site_location_text": string|null, "site_postcode": string|null, "site_town": string|null, "location_confidence": "high"|"medium"|"low", "est_workers_min": integer|null, "est_workers_max": integer|null, "est_workers_away_from_home": integer|null, "duration_months": integer|null, "start_date": "YYYY-MM-DD"|null}

Relevant means physical works needing on-site crews for 4+ weeks: construction, civils, rail, utilities, energy, M&E, demolition, major refurbishment, or maintenance frameworks with site teams.
Not relevant: consultancy or design only, software/IT, supply-only, cleaning, catering, one-day jobs, grants.

Location rules:
- The site is where the work physically happens, not the buyer's or supplier's office.
- site_postcode must be copied exactly from the notice text. Never invent or guess a postcode; use null if none is given for the site.
- site_town is the nearest UK town or city to the site.
- location_confidence: "high" if the notice names the site address or postcode, "medium" if it names a specific town/area or asset (e.g. a named station or plant), "low" if you are inferring from the buyer's area or it covers many sites.

Workforce: estimate peak on-site workers from value, duration and work type (rule of thumb: roughly £1m of civils per 4-6 workers per year). est_workers_away_from_home is how many would typically travel and need accommodation (specialist and main-contractor crews on regional/remote sites travel more; urban local-authority maintenance travels less). Use null when you cannot estimate.`;

export function buildEnrichPrompt(p: EnrichmentInput): string {
  const lines = [
    `Title: ${p.title}`,
    `Buyer: ${p.buyer_name ?? "unknown"}${p.buyer_postcode ? ` (office postcode ${p.buyer_postcode})` : ""}`,
    `Supplier awarded: ${p.supplier_name ?? "unknown"}`,
    `Value: ${p.value_gbp ? `${formatGbpCompact(p.value_gbp)} (£${Math.round(p.value_gbp).toLocaleString("en-GB")})` : "not stated"}`,
    `CPV codes: ${p.cpv_codes.join(", ") || "none"}`,
    `Contract period: ${p.start_date ?? "?"} to ${p.end_date ?? "?"}${p.duration_months ? ` (${p.duration_months} months)` : ""}`,
    `Delivery locations: ${p.delivery_text ?? "not stated"}`,
    "",
    "Description:",
    truncate(p.description ?? "(none)", 6000),
  ];
  return lines.join("\n");
}

/** Validates model output. Postcodes not present in the notice are discarded. */
export function validateEnrichment(raw: unknown, source: EnrichmentInput): Enrichment {
  const o = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  const sourceText = [
    source.title,
    source.description,
    source.delivery_text,
    ...source.delivery_postcodes,
  ].join(" ");
  const knownPostcodes = new Set([...extractPostcodes(sourceText), ...source.delivery_postcodes]);
  let postcode = normalizePostcode(asString(o.site_postcode));
  let confidence = asEnum(o.location_confidence, LOCATION_CONFIDENCES, "low");
  if (postcode && !knownPostcodes.has(postcode)) {
    postcode = null;
    if (confidence === "high") confidence = "medium";
  }
  let min = asInt(o.est_workers_min, 0, 5000);
  let max = asInt(o.est_workers_max, 0, 5000);
  if (min != null && max != null && min > max) [min, max] = [max, min];
  let away = asInt(o.est_workers_away_from_home, 0, 5000);
  if (away != null && max != null && away > max) away = max;
  const reason = asString(o.relevance_reason, 400) ?? "";
  return {
    is_relevant: o.is_relevant === true,
    relevance_reason: reason.split(/\s+/).slice(0, 30).join(" "),
    project_type: asEnum(o.project_type, PROJECT_TYPES, "other"),
    site_location_text: asString(o.site_location_text, 300),
    site_postcode: postcode,
    site_town: asString(o.site_town, 100),
    location_confidence: confidence,
    est_workers_min: min,
    est_workers_max: max,
    est_workers_away_from_home: away,
    duration_months: asInt(o.duration_months, 0, 240) ?? source.duration_months,
    start_date: asIsoDate(o.start_date) ?? source.start_date,
  };
}

export function statusFromEnrichment(
  e: Pick<Enrichment, "is_relevant" | "location_confidence">
): RadarStatus {
  if (!e.is_relevant) return "rejected";
  return e.location_confidence === "low" ? "needs_review" : "qualified";
}
