// GENERATED by scripts/sync-core.mjs from packages/core/src. Do not edit; run `pnpm sync:core`.
import { fetchWithRetry, type FetchLike, type RetryOptions } from "./http.ts";
import type { LatLng } from "./types.ts";

const POSTCODE_RE = /\b(GIR ?0AA|[A-PR-UWYZ](?:[0-9]{1,2}|[A-HK-Y][0-9]{1,2}|[0-9][A-HJKPSTUW]|[A-HK-Y][0-9][ABEHMNPRVWXY])) ?([0-9][ABD-HJLNP-UW-Z]{2})\b/gi;
const OUTCODE_RE = /^[A-PR-UWYZ](?:[0-9]{1,2}|[A-HK-Y][0-9]{1,2}|[0-9][A-HJKPSTUW]|[A-HK-Y][0-9][ABEHMNPRVWXY])$/i;

export function normalizePostcode(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const compact = raw.toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (compact.length < 5 || compact.length > 7) return null;
  const pc = `${compact.slice(0, -3)} ${compact.slice(-3)}`;
  POSTCODE_RE.lastIndex = 0;
  const m = POSTCODE_RE.exec(pc);
  return m && m[0].length === pc.length ? pc : null;
}

export function extractPostcodes(text: string | null | undefined): string[] {
  if (!text) return [];
  const out = new Set<string>();
  for (const m of text.matchAll(POSTCODE_RE)) {
    const pc = normalizePostcode(m[0]);
    if (pc) out.add(pc);
  }
  return [...out];
}

export function outcodeOf(postcode: string): string | null {
  const pc = normalizePostcode(postcode);
  if (pc) return pc.split(" ")[0] ?? null;
  const t = postcode.trim().toUpperCase();
  return OUTCODE_RE.test(t) ? t : null;
}

const EARTH_RADIUS_MILES = 3958.8;

export function haversineMiles(a: LatLng, b: LatLng): number {
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * EARTH_RADIUS_MILES * Math.asin(Math.min(1, Math.sqrt(h)));
}

export function roundMiles(m: number): number {
  return m < 10 ? Math.round(m * 10) / 10 : Math.round(m);
}

export interface GeocodeResult extends LatLng {
  method: "postcode" | "outcode" | "town";
  matched: string;
  postcode?: string;
  town?: string;
}

const POSTCODES_IO = "https://api.postcodes.io";

interface PostcodesIoResponse<T> {
  status: number;
  result: T | null;
}

export interface GeocodeDeps {
  fetchImpl?: FetchLike;
  retry?: RetryOptions;
}

async function getJson<T>(url: string, deps: GeocodeDeps): Promise<T | null> {
  const res = await fetchWithRetry(url, {}, { retries: 3, ...deps.retry, fetchImpl: deps.fetchImpl });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`postcodes.io ${res.status} for ${url}`);
  const body = (await res.json()) as PostcodesIoResponse<T>;
  return body.result;
}

export async function geocodePostcode(postcode: string, deps: GeocodeDeps = {}): Promise<GeocodeResult | null> {
  const pc = normalizePostcode(postcode);
  if (!pc) return null;
  const r = await getJson<{ latitude: number | null; longitude: number | null; admin_district?: string }>(
    `${POSTCODES_IO}/postcodes/${encodeURIComponent(pc)}`,
    deps
  );
  if (!r || r.latitude == null || r.longitude == null) return null;
  return { lat: r.latitude, lng: r.longitude, method: "postcode", matched: pc, postcode: pc, town: r.admin_district };
}

export async function geocodeOutcode(outcode: string, deps: GeocodeDeps = {}): Promise<GeocodeResult | null> {
  const oc = outcodeOf(outcode);
  if (!oc) return null;
  const r = await getJson<{ latitude: number | null; longitude: number | null }>(
    `${POSTCODES_IO}/outcodes/${encodeURIComponent(oc)}`,
    deps
  );
  if (!r || r.latitude == null || r.longitude == null) return null;
  return { lat: r.latitude, lng: r.longitude, method: "outcode", matched: oc };
}

export async function geocodeTown(town: string, deps: GeocodeDeps = {}): Promise<GeocodeResult | null> {
  const q = town.trim();
  if (!q) return null;
  const r = await getJson<Array<{ latitude: number; longitude: number; name_1: string }>>(
    `${POSTCODES_IO}/places?q=${encodeURIComponent(q)}&limit=1`,
    deps
  );
  const first = r?.[0];
  if (!first) return null;
  return { lat: first.latitude, lng: first.longitude, method: "town", matched: first.name_1, town: first.name_1 };
}

/** Postcode first, then its outcode (for terminated postcodes), then town. */
export async function geocode(
  input: { postcode?: string | null; town?: string | null },
  deps: GeocodeDeps = {}
): Promise<GeocodeResult | null> {
  if (input.postcode) {
    const byPc = await geocodePostcode(input.postcode, deps);
    if (byPc) return byPc;
    const byOc = await geocodeOutcode(input.postcode, deps);
    if (byOc) return byOc;
  }
  if (input.town) return geocodeTown(input.town, deps);
  return null;
}

/** EWKT accepted by PostgREST for geography columns. */
export function toWktPoint(p: LatLng): string {
  return `SRID=4326;POINT(${p.lng} ${p.lat})`;
}
