// GENERATED by scripts/sync-core.mjs from packages/core/src. Do not edit; run `pnpm sync:core`.
export class JsonParseError extends Error {
  readonly raw: string;
  constructor(message: string, raw: string) {
    super(message);
    this.name = "JsonParseError";
    this.raw = raw;
  }
}

/** Parses model output that should be JSON but may be wrapped in fences or prose. */
export function parseJsonLoose<T = unknown>(text: string): T {
  const trimmed = text.trim();
  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidates = [trimmed];
  if (fenced?.[1]) candidates.push(fenced[1].trim());
  const firstBrace = firstIndexOfAny(trimmed, ["{", "["]);
  if (firstBrace >= 0) {
    const open = trimmed[firstBrace];
    const close = open === "{" ? "}" : "]";
    const last = trimmed.lastIndexOf(close);
    if (last > firstBrace) candidates.push(trimmed.slice(firstBrace, last + 1));
  }
  for (const c of candidates) {
    try {
      return JSON.parse(c) as T;
    } catch {
      // try next candidate
    }
  }
  throw new JsonParseError("Model output was not valid JSON", text);
}

function firstIndexOfAny(s: string, chars: string[]): number {
  const idx = chars.map((c) => s.indexOf(c)).filter((i) => i >= 0);
  return idx.length ? Math.min(...idx) : -1;
}

export function asString(v: unknown, max = 10_000): string | null {
  if (typeof v !== "string") return null;
  const t = v.trim();
  return t ? t.slice(0, max) : null;
}

export function asInt(v: unknown, min = -Infinity, max = Infinity): number | null {
  const n = typeof v === "string" ? Number(v.replace(/[,£\s]/g, "")) : v;
  if (typeof n !== "number" || !Number.isFinite(n)) return null;
  return Math.min(max, Math.max(min, Math.round(n)));
}

export function asEnum<T extends string>(v: unknown, allowed: readonly T[], fallback: T): T {
  return typeof v === "string" && (allowed as readonly string[]).includes(v) ? (v as T) : fallback;
}

export function asIsoDate(v: unknown): string | null {
  if (typeof v !== "string") return null;
  const m = v.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return null;
  const d = new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`);
  return Number.isNaN(d.getTime()) ? null : `${m[1]}-${m[2]}-${m[3]}`;
}
